# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Posts
    url: '#recent-posts'
    weight: 20
#   - name: Projects
#     url: '#projects'
#     weight: 30
  - name: Publications
    url: '#featured'
    weight: 40
  - name: Talks
    url: '#talks'
    weight: 50
  - name: Courses
    weight: 60
    identifier: courses
  - name: CH EN 5960 Molecular Simulations
    PageRef: course/mol-sim/_index.md
    weight: 10
    parent: courses
  - name: Contact
    url: '#contact'
    weight: 70
#   - name: CV
#     url: uploads/CV.pdf
#     weight: 70
